var edad = 27;
var peso = 75;
var sandwich = 1;
var jugarFutbol = -3;
var presioVino = 200.3;
// var total = presioVino * 3;
var total = presioVino * 100 * 3; // con esta se quita todos los decimales de la operacion
total = Math.round(presioVino * 100 * 3) / 100;
var totalStr = total.toFixed(2);
var total2 = parseFloat(totalStr);
var pizza = 8;
var persona = 2;
var totalPizza = pizza / persona;
//edad = edad +1;
edad += 1;
// peso -= 12;
// peso += sandwich;
peso = peso - jugarFutbol;
